version: 2.1
orbs:
  python: circleci/python@2.0.3

definitions:
  install-args: &install-args
      pkg-manager: pip-dist
      # use setup.cfg for caching, since that's where deps are
      pip-dependency-file: setup.cfg
      args: --editable .[dev]

jobs:
  lint:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages: *install-args
      - run:
          command: |
            cp .pre-commit-config.yaml pre-commit-cache-key.txt
            python --version --version >> pre-commit-cache-key.txt
      - restore_cache:
          key: v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
      - run: pre-commit run --all-files --show-diff-on-failure
      - save_cache:
          key: v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
          paths:
            - ~/.cache/pre-commit

  build-docs:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages: *install-args
      - run:
          name: Build docs
          working_directory: ./docs
          command: make html SPHINXOPTS='-W --keep-going'
      - persist_to_workspace:
          root: ./docs/_build
          paths:
            - html

  deploy-gh-pages:
    docker:
      - image: cimg/base:current
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ce:96:37:12:7d:fc:f8:98:36:18:b0:0d:d3:36:d5:b6"
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy docs
          command: |
            git checkout gh-pages
            # remove all old docs files
            git rm -r -- ':(exclude).nojekyll'
            # and replace with the new ones
            (shopt -s dotglob; cp --recursive /tmp/workspace/html/* .)
            git add .

            if ! git diff --cached --quiet
            then
                git config user.name "CircleCI"
                git config user.email "circleci@site.invalid"

                git commit --message "Deploy docs for: $CIRCLE_SHA1"
                git push origin HEAD
            else
                echo "No changes found, skipping deploy"
            fi

workflows:
  test-lint-deploy:
    jobs:
      - python/test:
          <<: *install-args
          matrix:
            parameters:
              version: ["3.7", "3.8", "3.9", "3.10"]
      - lint
      - build-docs
      - deploy-gh-pages:
          requires:
            - build-docs
          filters:
            branches:
              only:
                - master
